spring:
  application:
    name: order-system
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  country-api:
    base-url: https://www.apicountries.com

logging:
  level:
    com.mb.ordersystem.config.AopLoggingConfig: DEBUG
